name: workshop_flutter_performance
description: "Build method performance workshop"
publish_to: "none"
repository: "https://github.com/leventkantaroglu/workshop_flutter_performance"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
